### ISSUE TITLE
Feature Request: Add manage extension option which opens up chrome option page

### ISSUE THREAD

**Issue by Droyk** [luetage/extension_control#19]
this page is what I'm talking 'bout
![image](https://user-images.githubusercontent.com/15848350/99162250-ad4f6e00-2721-11eb-8cb3-23387b56ab33.png)

usually, I have to enable the extension and then only I can right-click to get this option!
![image](https://user-images.githubusercontent.com/15848350/99162288-0919f700-2722-11eb-8b84-70e5790e3513.png)

it would be time-saving to have this particular option in the right-clicking menu of extension control. will be great of user experience as well! 

---
by the way, I love your extension the best thing about this is the non-bloated design and I love dark theme as well as the light theme I don't want to move from your extension manager so please **UPDATE**!

**Comment by luetage** [comment]
Hi! I’m not on Chrome. If I click “Manage Extensions” in the context menu it takes me to the main extensions page, not to the “Details” page of a specific extension. The plural “Extensions” leads me to believe this is intended behavior.

**Comment by Droyk** [comment]
Um, I'm also not on the chrome I'm on edge Version 86.0.622.69 (Official Build) (64-bit)
though I just tested this on chrome, Brave & edge & I do get to the detail page, not on the main extension page!
I think you might be experiencing a browser issue!

>The plural “Extensions” leads me to believe this is intended behaviour.
it does though seems like a Little mistake to me. 

anyway if you can add the detail page option to your extension right-click context menu that would be a time saver!

**Comment by Droyk** [comment]
Umm hey man so any update on this?
I really like this extension manager's simplicity so I really don't like to use the alternatives because of their UI.
