### ISSUE TITLE
Feature Request: add searchbar on top to find extension easily!

### ISSUE THREAD

**Issue by Droyk** [luetage/extension_control#21]
Hey, I have close to 80 extensions. Yeah, I know they are a lot but each has its own uses. so if possible can you please add a search bar on top so I can find the extensions easily. better give the user an option to enable/disable the extension. so if the user doesn't like/want the search bar they can just easily disable it.

also, it would be really convenient if you can add fuzzy matching coz I don't remember complete extension names nor the correct order of their naming scheme so let's say if one extension name has Five words Youtube Auto 60 FPS HD I only need to type one of the words like this "You", "Youtube", "HD" or "FPS" and it will show me the related extension.

**Comment by luetage** [comment]
Ahoi there. Interesting idea, no promises.

**Comment by Droyk** [comment]
🥺🙏
