### ISSUE TITLE
Feature Request: Add a button on top to enable/disable all the current session extensions. 

### ISSUE THREAD

**Issue by Droyk** [luetage/extension_control#22]
Hey, it would be great if one can enable/disable all the currently enabled extensions in one quick sweep. sometimes I need to see what extension is causing the trouble, so I enable/disable extensions a lot & doing so takes a lot of time so it would be really time-saving. if you can add this feature to your extension manager.  

it would also be pretty damn convenient. if one can save the current session extension list and then make as many lists as one wants. like, let's say if I'm looking for a problematic extension. I immediately hit the disable button on the top. it saves the current session and disables all the extensions. now I enable some extensions and let's say I have to do some other work so I hit the disable button again & it automatically creates a new current session list and disables the extensions. when I come back I can just tell the extension to open the 1st list instead of the last one. It can look something like this 

![Ext 1](https://user-images.githubusercontent.com/15848350/129245166-64770e62-7410-4fe7-92d2-6063c8ca620e.png)
![Ext 2](https://user-images.githubusercontent.com/15848350/129245159-bdd7c183-58d9-4992-8d07-7da6da96672c.png)

I hope you really think about this feature as it will save a lot of headaches for a lot of users out there.
please just make it possible 🙏!

**Comment by Droyk** [comment]
@luetage think about all the 1000+ users you'll get. just think about it man. think about that 5+ rating for a second!. fine if this doesn't motivate you, what about making your extension a little bit better compared to the alternatives? your words
>Why another extension manager
We felt that the current extension managers available for chromium browsers had features we didn't need and **mostly dated,** bloated design. **Extension Control adjusts to your needs and preferences.**

The irony of it is your own extension has become **dated.** and you're not making your extension adjust to your users' needs. Good looks only aren't going to cut the deal. it is what is inside that matters not how it looks. Yes, looks are pleasing to the eyes but if it doesn't provide an equal amount of functionality it's not going to matter at all.
by adding all these features it will still be simple enough to use for sure but it will also be efficient at what it does. how about while trying to add these features you will be able to learn some new things which could help you immensely in future or just makes you improve your skills if this can't motivate you IDK what can, man?
Just please add them!

**Comment by luetage** [comment]
Should groups be added, which is the most requested feature, this functionality would be part of it.

**Comment by Droyk** [comment]
>Should groups are added,

So otherwise, there's no chance of this request to make it to the extension.
What a time waste. I tried my best to motivate you, man.
you seem to have no motivation at all. 
You shouldn't have published this extension.

**Comment by luetage** [comment]
Let’s make one thing clear: We do not owe you anything. You are using an open source extension free of charge. We made the extension, because we needed a simple way to toggle extensions and the other managers didn’t cut it. The project went well so we shared it with the community. Throwing a hissy fit and trying to bully to get your way doesn’t impress me. Luckily you are not the only one wanting groups, so this might still come in due time.

**Comment by Droyk** [comment]
>Let’s make one thing clear: We do not owe you anything. 

I'm pretty much aware of that. & I made sure that wasn't what my comment implied but it seems like you took it that way. it suggested anger, immaturity sure but not a sense of ownership. I was also angry at myself for not being able to contribute to this project coz I haven't learn to code I wanted to but took a turn doing something else at the moment & don't have much free time to learn it now. 

>Throwing a hissy fit and trying to bully to get your way doesn’t impress me. 

lol.. Well, I tried every other option so... I thought might as well see how this one goes? and luckily I got some response to it.😋😉
>Luckily you are not the only one wanting groups, so this might still come in due time.

I hope it will be soon. & I hope you gain enough motivation to see this to the very end.

**Comment by Droyk** [comment]
>Luckily you are not the only one wanting groups, so this might still come in due time.

Also, I didn't request to add groups. I requested a quick sweep way to get them to enable/disable in a way the user can go back and quickly enable what they disabled. to achieve that I purposed a way in which the minute the user hit disable button the extension automatically saves the current session list that saves active extensions that were present in the current session.

while one can also use the saving/restoring function to make groups you can add it without investing your time in making groups. it doesn't need grouping functionality. if you add this it will be like Getting two giggles from one tickle.

**Comment by Droyk** [comment]
> Throwing a hissy fit and trying to bully to get your way doesn’t impress me.

it wasn't meant to impress you. it was meant to get your attention that it is finally the time to do something about your extension. It can achieve something. your execution had that potential in it. as of right now the extension lacking many core features to make it any useful. to attract other developers to help you on this open-source project you have to do a bit of hard work first yourself. 

<sup>forgot to say this yesterday.<sup>¯\\\_(ツ)_/¯</sup></sup>
